enum EventType {
  AskSellerQuestion = 'AskSellerQuestion',
  BestOffer = 'BestOffer',
  BestOfferDeclined = 'BestOfferDeclined',
  BestOfferPlaced = 'BestOfferPlaced',
  BidPlaced = 'BidPlaced',
  BidReceived = 'BidReceived',
  CounterOfferReceived = 'CounterOfferReceived',
  CustomCode = 'CustomCode',
  EndOfAuction = 'EndOfAuction',
  FeedbackLeft = 'FeedbackLeft',
  FeedbackReceived = 'FeedbackReceived',
  FeedbackStarChanged = 'FeedbackStarChanged',
  FixedPriceEndOfTransaction = 'FixedPriceEndOfTransaction',
  FixedPriceTransaction = 'FixedPriceTransaction',
  ItemAddedToWatchList = 'ItemAddedToWatchList',
  ItemEnded = 'ItemEnded',
  ItemListed = 'ItemListed',
  ItemLost = 'ItemLost',
  ItemMarkedPaid = 'ItemMarkedPaid',
  ItemMarkedShipped = 'ItemMarkedShipped',
  ItemRemovedFromWatchList = 'ItemRemovedFromWatchList',
  ItemSold = 'ItemSold',
  ItemUnsold = 'ItemUnsold',
  ItemWon = 'ItemWon',
  OutBid = 'OutBid',
  PriceChange = 'PriceChange',
  SecondChanceOffer = 'SecondChanceOffer',
  WatchedItemEndingSoon = 'WatchedItemEndingSoon'
}

export {EventType};
