// https://developer.ebay.com/Devzone/XML/docs/Reference/eBay/GetAccount.html#Output
import type { CurrencyCodeType, StandardOutputFields } from './common.js';

export interface GetAccountResponse extends StandardOutputFields {
  AccountEntries: {
    AccountEntry?: {
      AccountDetailsEntryType?:
        | 'AccountStateSwitch'
        | 'AdFeeExpress'
        | 'AdFeeExpressCredit'
        | 'AdFeePremium'
        | 'AdFeePremiumCredit'
        | 'AllFeesCredit'
        | 'AUPostReturnLabelFee'
        | 'AUPostReturnLabelFeeCredit'
        | 'AustraliaGST'
        | 'AustraliaGSTCredit'
        | 'AWCredit'
        | 'AWDebit'
        | 'AWMemo'
        | 'BankPayoutFee'
        | 'BankPayoutFeeCredit'
        | 'BBAdminCredit'
        | 'BBAdminDebit'
        | 'BulkUserSuspension'
        | 'BuyItNowCredit'
        | 'BuyItNowFee'
        | 'CanadaPostLabelFee'
        | 'CanadaPostLabelFeeCredit'
        | 'CAPostReturnLabelFee'
        | 'CAPostReturnLabelFeeCredit'
        | 'CCNotOnFilePerCustReq'
        | 'CCPaymentRejected'
        | 'ChargeBack'
        | 'ChargeBackReversal'
        | 'Chargeoff'
        | 'ChargeoffBankruptcy'
        | 'ChargeoffDeceased'
        | 'ChargeoffOther'
        | 'ChargeoffRecovery'
        | 'ChargeoffSuspended'
        | 'ChargeoffWacko'
        | 'CharityDonation'
        | 'CharityDonationCredit'
        | 'CoFundingCharge'
        | 'CoFundingChargeCredit'
        | 'CreditAd'
        | 'CreditAPACFedExShippingLabel'
        | 'CreditAPACTNTShippingLabel'
        | 'CreditAuctionEndEarly'
        | 'CreditAUPostShippingLabel'
        | 'CreditBold'
        | 'CreditCardNotOnFile'
        | 'CreditCardOnFile'
        | 'CreditCategoryFeatured'
        | 'CreditCourtesy'
        | 'CreditDuplicateListing'
        | 'CrediteBayMotorsProFeatureFee'
        | 'CrediteBayMotorsProFee'
        | 'CrediteBayPlusSubscription'
        | 'CrediteBayStores'
        | 'CreditEBPReimbursement'
        | 'CreditEquifaxRealtimeFee'
        | 'CreditFeatured'
        | 'CreditFeaturedGallery'
        | 'CreditFedExShippingLabel'
        | 'CreditFinalValue'
        | 'CreditFinalValueFixedPrice'
        | 'CreditFinalValueShipping'
        | 'CreditGallery'
        | 'CreditGalleryPlus'
        | 'CreditGlobalShippingProgram'
        | 'CreditInsertion'
        | 'CreditInsertionFee'
        | 'CreditInsertionFixedPrice'
        | 'CreditIPIXPhoto'
        | 'CreditIPIXSlideShow'
        | 'CreditLargePicture'
        | 'CreditNoSale'
        | 'CreditPartialSale'
        | 'CreditPCGS'
        | 'CreditPictureShow'
        | 'CreditPrivateListing'
        | 'CreditPSA'
        | 'CreditRealEstate30DaysListing'
        | 'CreditReserve'
        | 'CreditReturnRefund'
        | 'CreditReturnShipping'
        | 'CreditSchedule'
        | 'CreditSMBasic'
        | 'CreditSMBasicPro'
        | 'CreditSoftOutage'
        | 'CreditStoresSubscriptionEarlyTermination'
        | 'CreditTenDayAuction'
        | 'CreditTransferFrom'
        | 'CreditUBIShippingLabel'
        | 'CreditVehicleSubscription'
        | 'CreditVehicleSubscriptionEarlyTermination'
        | 'CustomCode'
        | 'DebitTransferTo'
        | 'DepositProcessingFee'
        | 'DepositProcessingFeeCredit'
        | 'DHLPaymentProcessingFee'
        | 'DHLPaymentProcessingFeeCredit'
        | 'DHLReturnLblShippingFee'
        | 'DHLReturnLblShippingFeeCredit'
        | 'DirectDebitNotOnFile'
        | 'DirectDebitOnFile'
        | 'DirectDebitReturnedItem'
        | 'DirectDebitReversal'
        | 'Discount'
        | 'eBayCredit'
        | 'eBayDebit'
        | 'eBayMotorsProFeatureFee'
        | 'eBayMotorsProFee'
        | 'EbaySendLabelFee'
        | 'EbaySendLabelFeeCredit'
        | 'eBayVISACredit'
        | 'EOMRestriction'
        | 'EPRFee'
        | 'EPRFeeCredit'
        | 'EquifaxRealtimeFee'
        | 'ExpressPayoutFee'
        | 'ExpressPayoutFeeCredit'
        | 'ExtendedDurationFee'
        | 'ExtendedDurationFeeCredit'
        | 'FedExCaLabelFee'
        | 'FedExCaLabelFeeCredit'
        | 'FedExReturnLabelFee'
        | 'FedExReturnLabelFeeCredit'
        | 'FeeAd'
        | 'FeeAPACFedExShippingLabel'
        | 'FeeAPACTNTShippingLabel'
        | 'FeeAuctionEndEarly'
        | 'FeeAUPostShippingLabel'
        | 'FeeBold'
        | 'FeeCategoryFeatured'
        | 'FeeeBayPlusSubscription'
        | 'FeeEBPReimbursement'
        | 'FeeFeatured'
        | 'FeeFeaturedGallery'
        | 'FeeFedExShippingLabel'
        | 'FeeFinalValue'
        | 'FeeFinalValueFixedPrice'
        | 'FeeFinalValueShipping'
        | 'FeeGallery'
        | 'FeeGalleryPlus'
        | 'FeeGlobalShippingProgram'
        | 'FeeInsertion'
        | 'FeeInsertionFixedPrice'
        | 'FeeIPIXPhoto'
        | 'FeeIPIXSlideShow'
        | 'FeeLargePicture'
        | 'FeeNSFCheck'
        | 'FeePartialSale'
        | 'FeePaymentIntermediationChargeback'
        | 'FeePaymentIntermediationChargebackRVI'
        | 'FeePaymentIntermediationRVI'
        | 'FeeRealEstate30DaysListing'
        | 'FeeRedepositCheck'
        | 'FeeReserve'
        | 'FeeReturnCheckClose'
        | 'FeeReturnedCheck'
        | 'FeeReturnRefund'
        | 'FeeReturnShipping'
        | 'FeeSchedule'
        | 'FeeStoresSubscriptionEarlyTermination'
        | 'FeeTenDayAuction'
        | 'FeeUBIShippingLabel'
        | 'FeeVehicleSubscription'
        | 'FeeVehicleSubscriptionEarlyTermination'
        | 'FinalEntry'
        | 'FinalValueFee'
        | 'FinalValueFeeBelowStandard'
        | 'FinalValueFeeBelowStandardCredit'
        | 'FinalValueFeeCredit'
        | 'FinalValueFeeFixedFeePerOrder'
        | 'FinalValueFeeFixedFeePerOrderCredit'
        | 'FinanceCharge'
        | 'FinanceChargeReversal'
        | 'FixedPriceDurationCredit'
        | 'FixedPriceDurationFee'
        | 'FlagDDDDPending'
        | 'FlagDDPaymentConfirmed'
        | 'ForeignFundsCheckReversal'
        | 'ForeignFundsConvert'
        | 'FVFCreditReversal'
        | 'FVFCreditReversalAutomatic'
        | 'HermesReturnLabelFee'
        | 'HermesReturnLabelFeeCredit'
        | 'HermesReturnLblSellerPaidShpFee'
        | 'HermesReturnLblSellerPaidShpFeeCr'
        | 'HighlineSearchFee'
        | 'HighlineSearchFeeCredit'
        | 'HubbedReturnLabelFee'
        | 'HubbedReturnLabelFeeCredit'
        | 'InternationalFee'
        | 'InternationalFeeCredit'
        | 'InternationalListingCredit'
        | 'InternationalListingFee'
        | 'InvoiceCreditBalance'
        | 'Invoiced'
        | 'InvoicedCreditCard'
        | 'ItemMoveFee'
        | 'MarketplaceResearchBasicSubscriptionFee'
        | 'MarketplaceResearchBasicSubscriptionFeeCredit'
        | 'MarketplaceResearchExpiredSubscriptionFee'
        | 'MarketplaceResearchExpiredSubscriptionFeeCredit'
        | 'MarketplaceResearchProSubscriptionFee'
        | 'MarketplaceResearchProSubscriptionFeeCredit'
        | 'Memo'
        | 'Merged'
        | 'NewZealandGST'
        | 'NewZealandGSTCredit'
        | 'OffsiteAdsFee'
        | 'OffsiteAdsFeeCredit'
        | 'OutageCredit'
        | 'ParcelForcePostReturnLabelFee'
        | 'ParcelForcePostReturnLabelFeeCredit'
        | 'PaymentAdjustmentCredit'
        | 'PaymentAdjustmentDebit'
        | 'PaymentCash'
        | 'PaymentCC'
        | 'PaymentCCOnce'
        | 'PaymentCheck'
        | 'PaymentDirectDebit'
        | 'PaymentElectronicTransfer'
        | 'PaymentElectronicTransferReversal'
        | 'PaymentEquifaxCredit'
        | 'PaymentEquifaxDebit'
        | 'PaymentGiftCertificate'
        | 'PaymentHomeBanking'
        | 'PaymentIntermediationFee'
        | 'PaymentIntermediationFeeCredit'
        | 'PaymentMoneyOrder'
        | 'PaymentWireTransfer'
        | 'PerListingPaymentsFee'
        | 'PerListingPaymentsFeeCredit'
        | 'PrivateListing'
        | 'PromotedDisplayFee'
        | 'PromotedDisplayFeeCredit'
        | 'PromotionalCredit'
        | 'ProPackBundleFee'
        | 'ProPackBundleFeeCredit'
        | 'ProPackPlusBundleFee'
        | 'ProPackPlusBundleFeeCredit'
        | 'ReferrerCredit'
        | 'ReferrerDebit'
        | 'RefundCC'
        | 'RefundCheck'
        | 'RegulatoryOperatingFee'
        | 'RegulatoryOperatingFeeCredit'
        | 'RevertUserState'
        | 'RoyalMailReturnLabelFee'
        | 'RoyalMailReturnLabelFeeCredit'
        | 'SalesReportsPlusCredit'
        | 'SalesReportsPlusFee'
        | 'SendLabelFee'
        | 'SendLabelFeeCredit'
        | 'SetOnHold'
        | 'ShippingInsuranceFee'
        | 'ShippingInsuranceFeeCredit'
        | 'SnadOutlierFinalValueFee'
        | 'SnadOutlierFinalValueFeeCredit'
        | 'SnadOutlierFinalValueFeeOnShipping'
        | 'SnadOutlierFinalValueFeeOnShippingCredit'
        | 'StoresGTCCredit'
        | 'StoresGTCFee'
        | 'SubscriptioneBayStores'
        | 'SubscriptionSMBasic'
        | 'SubscriptionSMBasicPro'
        | 'SubtitleFee'
        | 'SubtitleFeeCredit'
        | 'SwitchCurrency'
        | 'TemporaryCredit'
        | 'TemporaryCreditReversal'
        | 'Unknown'
        | 'UpsCaLabelFee'
        | 'UpsCaLabelFeeCredit'
        | 'UpsLabelFee'
        | 'UpsLabelFeeCredit'
        | 'USInternetSalesTax'
        | 'USInternetSalesTaxCredit'
        | 'UspsLabelFee'
        | 'UspsLabelFeeCredit'
        | 'UspsShortpaidFee'
        | 'UspsShortpaidFeeCredit'
        | 'USWHTFederal'
        | 'USWHTFederalCredit'
        | 'USWHTState'
        | 'USWHTStateCredit'
        | 'ValuePackBundleFee'
        | 'ValuePackBundleFeeCredit'
        | 'VATCredit'
        | 'VATDebit'
        | 'VATStatusChange_Denied'
        | 'VATStatusChangeApproved'
        | 'VATStatusChangePending'
        | 'VATStatusDeletedByCSR'
        | 'VATStatusDeletedByUser'
        | 'VehicleLocalFinalValueFee'
        | 'VehicleLocalFinalValueFeeCredit'
        | 'VehicleLocalGTCFee'
        | 'VehicleLocalGTCFeeCredit'
        | 'VehicleLocalInsertionFee'
        | 'VehicleLocalInsertionFeeCredit'
        | 'VehicleLocalSubscriptionFee'
        | 'VehicleLocalSubscriptionFeeCredit'
        | 'VehiclesListingBasicPackageCredit'
        | 'VehiclesListingBasicPackageFee'
        | 'VehiclesListingPlusPackageCredit'
        | 'VehiclesListingPlusPackageFee'
        | 'VehiclesListingPremiumPackageCredit'
        | 'VehiclesListingPremiumPackageFee';
      Balance?: number | { value: number; currencyID: CurrencyCodeType };
      ConversionRate?: number | { value: number; currencyID: CurrencyCodeType };
      Date?: string;
      Description?: string;
      DiscountDetail?: {
        Discount?: {
          Amount?: number | { value: number; currencyID: CurrencyCodeType };
          DiscountType?: string;
        };
      };
      GrossDetailAmount?:
        | number
        | { value: number; currencyID: CurrencyCodeType };
      ItemID?: string;
      Memo?: string;
      NetDetailAmount?:
        | number
        | { value: number; currencyID: CurrencyCodeType };
      Netted?: boolean;
      OrderId?: string;
      OrderLineItemID?: string;
      ReceivedTopRatedDiscount?: boolean;
      RefNumber?: string;
      Title?: string;
      TransactionID?: string;
      VATPercent?: number;
    };
  };
  AccountID: string;
  AccountSummary?: {
    AccountState?: 'Active' | 'CustomCode' | 'Inactive' | 'Pending';
    AdditionalAccount?: {
      AccountCode?: string;
      Balance?: number | { value: number; currencyID: CurrencyCodeType };
      Currency?: CurrencyCodeType;
    };
    AmountPastDue?: number | { value: number; currencyID: CurrencyCodeType };
    BankAccountInfo?: string;
    BankModifyDate?: string;
    BillingCycleDate?: number;
    CreditCardExpiration?: string;
    CreditCardInfo?: string;
    CreditCardModifyDate?: string;
    CurrentBalance?: number | { value: number; currencyID: CurrencyCodeType };
    InvoiceBalance?: number | { value: number; currencyID: CurrencyCodeType };
    InvoiceCredit?: number | { value: number; currencyID: CurrencyCodeType };
    InvoiceDate?: string;
    InvoiceNewFee?: number | { value: number; currencyID: CurrencyCodeType };
    InvoicePayment?: number | { value: number; currencyID: CurrencyCodeType };
    LastAmountPaid?: number | { value: number; currencyID: CurrencyCodeType };
    LastPaymentDate?: string;
    NettedTransactionSummary?: {
      TotalNettedChargeAmount?:
        | number
        | { value: number; currencyID: CurrencyCodeType };
      TotalNettedCreditAmount?:
        | number
        | { value: number; currencyID: CurrencyCodeType };
    };
    PastDue?: boolean;
    PaymentMethod?:
      | 'CreditCard'
      | 'CustomCode'
      | 'DirectDebit'
      | 'DirectDebitPendingSignatureMandate'
      | 'DirectDebitPendingVerification'
      | 'eBayDirectPay'
      | 'NothingOnFile'
      | 'PayPal';
  };
  Currency: CurrencyCodeType;
  EntriesPerPage: number;
  FeeNettingStatus: 'Disabled' | 'Enabled' | 'Exempted';
  HasMoreEntries?: boolean;
  PageNumber: number;
  PaginationResult: {
    TotalNumberOfEntries: number;
    TotalNumberOfPages: number;
  };
}
