// https://developer.ebay.com/Devzone/XML/docs/Reference/eBay/GeteBayDetails.html#Output
import type {
  CountryCodeType,
  CurrencyCodeType,
  StandardOutputFields
} from './common.js';

export interface GeteBayDetailsResponse extends StandardOutputFields {
  BuyerRequirementDetails: {
    DetailVersion: string;
    LinkedPayPalAccount?: boolean;
    MaximumBuyerPolicyViolations?: {
      NumberOfPolicyViolations?: any;
      PolicyViolationDuration?: {
        Description?: string;
        Period?: 'CustomCode' | 'Days_180' | 'Days_30' | 'Days_360';
      };
    };
    MaximumItemRequirements?: {
      MaximumItemCount?: number;
      MinimumFeedbackScore?: number;
    };
    MaximumUnpaidItemStrikesInfo?: {
      MaximumUnpaidItemStrikesCount?: {
        Count?: number;
      };
      MaximumUnpaidItemStrikesDuration?: {
        Description?: string;
        Period?: 'CustomCode' | 'Days_180' | 'Days_30' | 'Days_360';
      };
    };
    MinimumFeedbackScore?: any;
    ShipToRegistrationCountry?: boolean;
    UpdateTime: string;
  };
  CountryDetails?: {
    Country?: CountryCodeType;
    Description?: string;
    DetailVersion: string;
    UpdateTime: string;
  };
  CurrencyDetails?: {
    Currency?: CurrencyCodeType;
    Description?: string;
    DetailVersion: string;
    UpdateTime: string;
  };
  DispatchTimeMaxDetails?: {
    Description?: string;
    DetailVersion: string;
    DispatchTimeMax?: number;
    ExtendedHandling: boolean;
    UpdateTime: string;
  };
  ExcludeShippingLocationDetails?: {
    Description?: string;
    DetailVersion?: string;
    Location?: string;
    Region?: string;
    UpdateTime?: string;
  };
  ItemSpecificDetails?: {
    DetailVersion: string;
    MaxCharactersPerName?: number;
    MaxCharactersPerValue?: number;
    MaxItemSpecificsPerItem?: number;
    MaxValuesPerName?: number;
    UpdateTime: string;
  };
  ListingFeatureDetails?: {
    BoldTitle: 'CustomCode' | 'Disabled' | 'Enabled';
    Border: string;
    DetailVersion: string;
    FeaturedFirst:
      | 'CustomCode'
      | 'Disabled'
      | 'Enabled'
      | 'PowerSellerOnly'
      | 'TopRatedSellerOnly';
    FeaturedPlus:
      | 'CustomCode'
      | 'Disabled'
      | 'Enabled'
      | 'PowerSellerOnly'
      | 'TopRatedSellerOnly';
    GiftIcon: string;
    Highlight: string;
    HomePageFeatured: 'CustomCode' | 'Disabled' | 'Enabled';
    ProPack: string;
    UpdateTime: string;
  };
  ListingStartPriceDetails?: {
    Description?: string;
    DetailVersion: string;
    ListingType?:
      | 'AdType'
      | 'Auction'
      | 'Chinese'
      | 'CustomCode'
      | 'FixedPriceItem'
      | 'LeadGeneration'
      | 'PersonalOffer'
      | 'Unknown';
    MinBuyItNowPricePercent?: number;
    StartPrice?: number | { value: number; currencyID: CurrencyCodeType };
    UpdateTime: string;
  };
  PaymentOptionDetails?: {
    Description?: string;
    DetailVersion?: string;
    PaymentOption?:
      | 'CashOnPickup'
      | 'COD'
      | 'CustomCode'
      | 'MOCC'
      | 'PersonalCheck';
    UpdateTime?: string;
  };
  ProductDetails?: {
    ProductIdentifierUnavailableText?: string;
  };
  RecoupmentPolicyDetails?: {
    DetailVersion: string;
    EnforcedOnListingSite: boolean;
    EnforcedOnRegistrationSite: boolean;
    UpdateTime: string;
  };
  RegionDetails?: {
    Description?: string;
    DetailVersion?: string;
    RegionID?: string;
    UpdateTime?: string;
  };
  RegionOfOriginDetails?: {
    Description?: string;
    DetailVersion?: string;
    RegionOfOrigin?: string;
    Status?: any;
    UpdateTime?: string;
  };
  ReturnPolicyDetails?: {
    Description?: boolean;
    DetailVersion: string;
    Refund?: {
      Description?: string;
      RefundOption?: string;
    };
    ReturnsAccepted?: {
      Description?: string;
      ReturnsAcceptedOption?: string;
    };
    ReturnsWithin?: {
      Description?: string;
      ReturnsWithinOption?: string;
    };
    ShippingCostPaidBy?: {
      Description?: string;
      ShippingCostPaidByOption?: string;
    };
    UpdateTime: string;
  };
  ShippingCarrierDetails?: {
    Description?: string;
    DetailVersion: string;
    ShippingCarrier?:
      | 'A1CourierServices'
      | 'ABF'
      | 'AeroPost'
      | 'ALLIEDEXPRESS'
      | 'AMWST'
      | 'AnPost'
      | 'APC'
      | 'ARAMEX'
      | 'ARVATO'
      | 'ASM'
      | 'AustralianAirExpress'
      | 'AustraliaPost'
      | 'AVRT'
      | 'Bartolini'
      | 'BELGIANPOST'
      | 'BKNS'
      | 'BluePackage'
      | 'BPost'
      | 'BusinessPost'
      | 'CanPar'
      | 'CENF'
      | 'CEVA'
      | 'ChinaPost'
      | 'Chronoexpres'
      | 'Chronopost'
      | 'CHUKOU1'
      | 'ChunghwaPost'
      | 'CitiPost'
      | 'CityLink'
      | 'ClickandQuick'
      | 'CNWY'
      | 'ColiposteDomestic'
      | 'ColiposteInternational'
      | 'Colissimo'
      | 'CollectPlus'
      | 'Correos'
      | 'CPC'
      | 'CustomCode'
      | 'DAIPost'
      | 'DayandRoss'
      | 'DBSchenker'
      | 'DeutschePost'
      | 'DHL'
      | 'DHLEKB'
      | 'DHLEXPRESS'
      | 'DHLG'
      | 'DHLGlobalMail'
      | 'DieSchweizerischePost'
      | 'DPD'
      | 'DPXThailand'
      | 'Ducros'
      | 'EGO'
      | 'EMF'
      | 'Exapaq'
      | 'Fastway'
      | 'FASTWAYCOURIERS'
      | 'FedEx'
      | 'FedExSmartPost'
      | 'FLYT'
      | 'FLYTExpress'
      | 'FlytExpressUSDirectline'
      | 'FourPX'
      | 'FourPXCHINA'
      | 'FourPXExpress'
      | 'FourPXLTD'
      | 'FTFT'
      | 'FulfilExpressAccStation'
      | 'FulfilExpresseForCity'
      | 'FulfilExpressEverydaySource'
      | 'FulfilExpressiTrimming'
      | 'GLS'
      | 'HDUSA'
      | 'Hermes'
      | 'HomeDeliveryNetwork'
      | 'HongKongPost'
      | 'HUNTEREXPRESS'
      | 'iLoxx'
      | 'IndiaPost'
      | 'IndonesiaPost'
      | 'Interlink'
      | 'InterPost'
      | 'IoInvio'
      | 'Iparcel'
      | 'IsraelPost'
      | 'JapanPost'
      | 'KIALA'
      | 'KoreaPost'
      | 'Landmark'
      | 'LAPOSTE'
      | 'LDSO'
      | 'LTL'
      | 'MALAYSIAPOST'
      | 'MannaFreight'
      | 'Metapack'
      | 'MNGTurkey'
      | 'MondialRelay'
      | 'MRW'
      | 'MSI'
      | 'Nacex'
      | 'NEMF'
      | 'ODFL'
      | 'OFFD'
      | 'ONTRACK'
      | 'OsterreichischePostAG'
      | 'Other'
      | 'OVNT'
      | 'Parcelforce'
      | 'ParcelPool'
      | 'Philpost'
      | 'Pilot'
      | 'PITD'
      | 'PocztaPolska'
      | 'Pocztex'
      | 'PosteItaliane'
      | 'POSTITALIANO'
      | 'PostNL'
      | 'PostNordNorway'
      | 'Prestige'
      | 'Quantium'
      | 'RETL'
      | 'RoyalMail'
      | 'RRUN'
      | 'SAIA'
      | 'SDA'
      | 'Seur'
      | 'SevenLSP'
      | 'SFC'
      | 'SFCExpress'
      | 'SINGAPOREPOST'
      | 'Siodemka'
      | 'SioliandFontana'
      | 'SkynetMalaysia'
      | 'SMARTSEND'
      | 'Sogetras'
      | 'Spediamo'
      | 'SpeeDee'
      | 'StarTrack'
      | 'SuntekExpressLTD'
      | 'SwissPost'
      | 'TELE'
      | 'TEMANDO'
      | 'THAILANDPOST'
      | 'TNT'
      | 'TNTEXPRESS'
      | 'TNTPost'
      | 'Toll'
      | 'TPG'
      | 'TWW'
      | 'UBI'
      | 'UKMail'
      | 'UPS'
      | 'UPSC'
      | 'UPSMailInnovations'
      | 'USFG'
      | 'USPS'
      | 'USPSCeP'
      | 'USPSPMI'
      | 'VietnamPost'
      | 'VITR'
      | 'WATKINS'
      | 'Winit'
      | 'Wise'
      | 'WNdirect'
      | 'WPX'
      | 'YANWEN'
      | 'Yodel'
      | 'YRC';
    ShippingCarrierID?: number;
    UpdateTime: string;
  };
  ShippingCategoryDetails?: {
    Description?: string;
    DetailVersion: string;
    ShippingCategory?: string;
    UpdateTime: string;
  };
  ShippingLocationDetails?: {
    Description?: string;
    DetailVersion: string;
    ShippingLocation?: string;
    UpdateTime: string;
  };
  ShippingPackageDetails?: {
    DefaultValue?: boolean;
    Description?: string;
    DetailVersion: string;
    DimensionsSupported?: boolean;
    PackageID?: number;
    ShippingPackage?:
      | 'BulkyGoods'
      | 'Caravan'
      | 'Cars'
      | 'CustomCode'
      | 'Europallet'
      | 'ExpandableToughBags'
      | 'ExtraLargePack'
      | 'Furniture'
      | 'IndustryVehicles'
      | 'LargeCanadaPostBox'
      | 'LargeCanadaPostBubbleMailer'
      | 'LargeEnvelope'
      | 'Letter'
      | 'MailingBoxes'
      | 'MediumCanadaPostBox'
      | 'MediumCanadaPostBubbleMailer'
      | 'Motorbikes'
      | 'None'
      | 'OneWayPallet'
      | 'PackageThickEnvelope'
      | 'PaddedBags'
      | 'ParcelOrPaddedEnvelope'
      | 'Roll'
      | 'SmallCanadaPostBox'
      | 'SmallCanadaPostBubbleMailer'
      | 'ToughBags'
      | 'UPSLetter'
      | 'USPSFlatRateEnvelope'
      | 'USPSLargePack'
      | 'VeryLargePack'
      | 'Winepak';
    UpdateTime: string;
  };
  ShippingServiceDetails?: {
    CostGroupFlat?: string;
    DeprecationDetails?: {
      AnnouncementStartTime?: string;
      EventTime?: string;
      MessageType?:
        | 'CustomCode'
        | 'Deprecation'
        | 'DeprecationAndMapping'
        | 'Mapping'
        | 'None';
    };
    Description: string;
    DetailVersion: string;
    DimensionsRequired?: boolean;
    ExpeditedService?: boolean;
    InternationalService?: boolean;
    MappedToShippingServiceID?: number;
    ServiceType?:
      | 'Calculated'
      | 'CalculatedDomesticFlatInternational'
      | 'CustomCode'
      | 'Flat'
      | 'FlatDomesticCalculatedInternational'
      | 'Free'
      | 'Freight'
      | 'FreightFlat'
      | 'NotSpecified';
    ShippingCarrier?:
      | 'A1CourierServices'
      | 'ABF'
      | 'AeroPost'
      | 'ALLIEDEXPRESS'
      | 'AMWST'
      | 'AnPost'
      | 'APC'
      | 'ARAMEX'
      | 'ARVATO'
      | 'ASM'
      | 'AustralianAirExpress'
      | 'AustraliaPost'
      | 'AVRT'
      | 'Bartolini'
      | 'BELGIANPOST'
      | 'BKNS'
      | 'BluePackage'
      | 'BPost'
      | 'BusinessPost'
      | 'CanPar'
      | 'CENF'
      | 'CEVA'
      | 'ChinaPost'
      | 'Chronoexpres'
      | 'Chronopost'
      | 'CHUKOU1'
      | 'ChunghwaPost'
      | 'CitiPost'
      | 'CityLink'
      | 'ClickandQuick'
      | 'CNWY'
      | 'ColiposteDomestic'
      | 'ColiposteInternational'
      | 'Colissimo'
      | 'CollectPlus'
      | 'Correos'
      | 'CPC'
      | 'CustomCode'
      | 'DAIPost'
      | 'DayandRoss'
      | 'DBSchenker'
      | 'DeutschePost'
      | 'DHL'
      | 'DHLEKB'
      | 'DHLEXPRESS'
      | 'DHLG'
      | 'DHLGlobalMail'
      | 'DieSchweizerischePost'
      | 'DPD'
      | 'DPXThailand'
      | 'Ducros'
      | 'EGO'
      | 'EMF'
      | 'Exapaq'
      | 'Fastway'
      | 'FASTWAYCOURIERS'
      | 'FedEx'
      | 'FedExSmartPost'
      | 'FLYT'
      | 'FLYTExpress'
      | 'FlytExpressUSDirectline'
      | 'FourPX'
      | 'FourPXCHINA'
      | 'FourPXExpress'
      | 'FourPXLTD'
      | 'FTFT'
      | 'FulfilExpressAccStation'
      | 'FulfilExpresseForCity'
      | 'FulfilExpressEverydaySource'
      | 'FulfilExpressiTrimming'
      | 'GLS'
      | 'HDUSA'
      | 'Hermes'
      | 'HomeDeliveryNetwork'
      | 'HongKongPost'
      | 'HUNTEREXPRESS'
      | 'iLoxx'
      | 'IndiaPost'
      | 'IndonesiaPost'
      | 'Interlink'
      | 'InterPost'
      | 'IoInvio'
      | 'Iparcel'
      | 'IsraelPost'
      | 'JapanPost'
      | 'KIALA'
      | 'KoreaPost'
      | 'Landmark'
      | 'LAPOSTE'
      | 'LDSO'
      | 'LTL'
      | 'MALAYSIAPOST'
      | 'MannaFreight'
      | 'Metapack'
      | 'MNGTurkey'
      | 'MondialRelay'
      | 'MRW'
      | 'MSI'
      | 'Nacex'
      | 'NEMF'
      | 'ODFL'
      | 'OFFD'
      | 'ONTRACK'
      | 'OsterreichischePostAG'
      | 'Other'
      | 'OVNT'
      | 'Parcelforce'
      | 'ParcelPool'
      | 'Philpost'
      | 'Pilot'
      | 'PITD'
      | 'PocztaPolska'
      | 'Pocztex'
      | 'PosteItaliane'
      | 'POSTITALIANO'
      | 'PostNL'
      | 'PostNordNorway'
      | 'Prestige'
      | 'Quantium'
      | 'RETL'
      | 'RoyalMail'
      | 'RRUN'
      | 'SAIA'
      | 'SDA'
      | 'Seur'
      | 'SevenLSP'
      | 'SFC'
      | 'SFCExpress'
      | 'SINGAPOREPOST'
      | 'Siodemka'
      | 'SioliandFontana'
      | 'SkynetMalaysia'
      | 'SMARTSEND'
      | 'Sogetras'
      | 'Spediamo'
      | 'SpeeDee'
      | 'StarTrack'
      | 'SuntekExpressLTD'
      | 'SwissPost'
      | 'TELE'
      | 'TEMANDO'
      | 'THAILANDPOST'
      | 'TNT'
      | 'TNTEXPRESS'
      | 'TNTPost'
      | 'Toll'
      | 'TPG'
      | 'TWW'
      | 'UBI'
      | 'UKMail'
      | 'UPS'
      | 'UPSC'
      | 'UPSMailInnovations'
      | 'USFG'
      | 'USPS'
      | 'USPSCeP'
      | 'USPSPMI'
      | 'VietnamPost'
      | 'VITR'
      | 'WATKINS'
      | 'Winit'
      | 'Wise'
      | 'WNdirect'
      | 'WPX'
      | 'YANWEN'
      | 'Yodel'
      | 'YRC';
    ShippingCategory?: string;
    ShippingPackage?:
      | 'BulkyGoods'
      | 'Caravan'
      | 'Cars'
      | 'CustomCode'
      | 'Europallet'
      | 'ExpandableToughBags'
      | 'ExtraLargePack'
      | 'Furniture'
      | 'IndustryVehicles'
      | 'LargeCanadaPostBox'
      | 'LargeCanadaPostBubbleMailer'
      | 'LargeEnvelope'
      | 'Letter'
      | 'MailingBoxes'
      | 'MediumCanadaPostBox'
      | 'MediumCanadaPostBubbleMailer'
      | 'Motorbikes'
      | 'None'
      | 'OneWayPallet'
      | 'PackageThickEnvelope'
      | 'PaddedBags'
      | 'ParcelOrPaddedEnvelope'
      | 'Roll'
      | 'SmallCanadaPostBox'
      | 'SmallCanadaPostBubbleMailer'
      | 'ToughBags'
      | 'UPSLetter'
      | 'USPSFlatRateEnvelope'
      | 'USPSLargePack'
      | 'VeryLargePack'
      | 'Winepak';
    ShippingService?: string;
    ShippingServiceID?: number;
    ShippingServicePackageDetails?: {
      DimensionsRequired?: boolean;
      Name?:
        | 'BulkyGoods'
        | 'Caravan'
        | 'Cars'
        | 'CustomCode'
        | 'Europallet'
        | 'ExpandableToughBags'
        | 'ExtraLargePack'
        | 'Furniture'
        | 'IndustryVehicles'
        | 'LargeCanadaPostBox'
        | 'LargeCanadaPostBubbleMailer'
        | 'LargeEnvelope'
        | 'Letter'
        | 'MailingBoxes'
        | 'MediumCanadaPostBox'
        | 'MediumCanadaPostBubbleMailer'
        | 'Motorbikes'
        | 'None'
        | 'OneWayPallet'
        | 'PackageThickEnvelope'
        | 'PaddedBags'
        | 'ParcelOrPaddedEnvelope'
        | 'Roll'
        | 'SmallCanadaPostBox'
        | 'SmallCanadaPostBubbleMailer'
        | 'ToughBags'
        | 'UPSLetter'
        | 'USPSFlatRateEnvelope'
        | 'USPSLargePack'
        | 'VeryLargePack'
        | 'Winepak';
    };
    ShippingTimeMax?: number;
    ShippingTimeMin?: number;
    SurchargeApplicable?: boolean;
    UpdateTime: string;
    ValidForSellingFlow?: boolean;
    WeightRequired?: boolean;
  };
  SiteDetails?: {
    DetailVersion: string;
    Site?:
      | 'Australia'
      | 'Austria'
      | 'Belgium_Dutch'
      | 'Belgium_French'
      | 'Canada'
      | 'CanadaFrench'
      | 'CustomCode'
      | 'Cyprus'
      | 'Czechia'
      | 'eBayMotors'
      | 'France'
      | 'Germany'
      | 'HongKong'
      | 'India'
      | 'Ireland'
      | 'Italy'
      | 'Malaysia'
      | 'Netherlands'
      | 'Philippines'
      | 'Poland'
      | 'Russia'
      | 'Singapore'
      | 'Spain'
      | 'Switzerland'
      | 'UK'
      | 'US';
    SiteID?: number;
    UpdateTime: string;
  };
  TaxJurisdiction?: {
    DetailVersion?: string;
    JurisdictionID?: string;
    JurisdictionName?: string;
    UpdateTime?: string;
  };
  TimeZoneDetails?: {
    DaylightSavingsInEffect?: boolean;
    DaylightSavingsLabel?: string;
    DaylightSavingsOffset?: string;
    DetailVersion: string;
    StandardLabel?: string;
    StandardOffset?: string;
    TimeZoneID?: string;
    UpdateTime: string;
  };
  URLDetails?: {
    DetailVersion: string;
    URL?: string;
    URLType?:
      | 'CustomCode'
      | 'eBayStoreURL'
      | 'LargeLogoURL'
      | 'MediumLogoURL'
      | 'MyeBayBiddingURL'
      | 'MyeBayNotWonURL'
      | 'MyeBayURL'
      | 'MyeBayWatchingURL'
      | 'MyeBayWonURL'
      | 'SmallLogoURL'
      | 'ViewItemURL'
      | 'ViewUserURL';
    UpdateTime: string;
  };
  UpdateTime: string;
  VariationDetails?: {
    DetailVersion: string;
    MaxNamesPerVariationSpecificsSet?: number;
    MaxValuesPerVariationSpecificsSetName?: number;
    MaxVariationsPerItem?: number;
    UpdateTime: string;
  };
}
